#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tgt
Version  : 1.0.69
Release  : 30
URL      : http://github.com/fujita/tgt/archive/v1.0.69.tar.gz
Source0  : http://github.com/fujita/tgt/archive/v1.0.69.tar.gz
Source1  : tgtd.service
Summary  : The SCSI target daemon and utility programs
Group    : Development/Tools
License  : GPL-2.0
Requires: tgt-bin
Requires: tgt-config
Requires: tgt-doc
BuildRequires : docbook-xml
BuildRequires : libxslt-bin
BuildRequires : systemd-dev
Patch1: build.patch

%description
The SCSI target package contains the daemon and tools to setup a SCSI targets.
Currently, software iSCSI targets are supported.

%package bin
Summary: bin components for the tgt package.
Group: Binaries
Requires: tgt-config

%description bin
bin components for the tgt package.


%package config
Summary: config components for the tgt package.
Group: Default

%description config
config components for the tgt package.


%package doc
Summary: doc components for the tgt package.
Group: Documentation

%description doc
doc components for the tgt package.


%prep
%setup -q -n tgt-1.0.69
%patch1 -p1

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489155786
make V=1  %{?_smp_mflags} SD_NOTIFY=1

%install
export SOURCE_DATE_EPOCH=1489155786
rm -rf %{buildroot}
%make_install
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/tgtd.service

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/tgt-admin
/usr/bin/tgt-setup-lun
/usr/bin/tgtadm
/usr/bin/tgtd
/usr/bin/tgtimg

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/tgtd.service

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/tgt/*
%doc /usr/share/man/man8/*
