#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : tgt
Version  : 1.0.60
Release  : 20
URL      : https://github.com/fujita/tgt/archive/v1.0.60.tar.gz
Source0  : https://github.com/fujita/tgt/archive/v1.0.60.tar.gz
Source1  : tgtd.service
Summary  : The SCSI target daemon and utility programs
Group    : Development/Tools
License  : GPL-2.0
Requires: tgt-bin
Requires: tgt-config
Requires: tgt-data
Requires: tgt-doc
BuildRequires : docbook-xml
BuildRequires : libxslt-bin
BuildRequires : systemd-dev
Patch1: 0001-Stateless.patch
Patch2: 0002-Default-config.patch

%description
The SCSI target package contains the daemon and tools to setup a SCSI targets.
Currently, software iSCSI targets are supported.

%package bin
Summary: bin components for the tgt package.
Group: Binaries
Requires: tgt-data
Requires: tgt-config

%description bin
bin components for the tgt package.


%package config
Summary: config components for the tgt package.
Group: Default

%description config
config components for the tgt package.


%package data
Summary: data components for the tgt package.
Group: Data

%description data
data components for the tgt package.


%package doc
Summary: doc components for the tgt package.
Group: Documentation

%description doc
doc components for the tgt package.


%prep
%setup -q -n tgt-1.0.60
%patch1 -p1
%patch2 -p1

%build
make V=1  %{?_smp_mflags} SD_NOTIFY=1

%install
rm -rf %{buildroot}
%make_install
mkdir -p %{buildroot}/usr/lib/systemd/system
install -m 0644 %{SOURCE1} %{buildroot}/usr/lib/systemd/system/tgtd.service

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/tgt-admin
/usr/bin/tgt-setup-lun
/usr/bin/tgtadm
/usr/bin/tgtd
/usr/bin/tgtimg

%files config
%defattr(-,root,root,-)
/usr/lib/systemd/system/tgtd.service

%files data
%defattr(-,root,root,-)
%exclude /usr/share/defaults/tgt/examples/targets.conf.example
%exclude /usr/share/defaults/tgt/examples/targets.conf.vtl.L700
%exclude /usr/share/defaults/tgt/examples/targets.conf.vtl.MSL2024
/usr/share/defaults/tgt/targets.conf

%files doc
%defattr(-,root,root,-)
%doc /usr/share/doc/tgt/*
%doc /usr/share/man/man8/*
